export interface CellConfig {
  id: string;
  level: number;
  title: string;
  position: number;
  nbParagraphs: number;
  color: string;
  blackText?: boolean;
  img: string;
}

export const cellsConfigs: CellConfig[] = [
  {
    id: 'fan',
    level: 1,
    title: 'F-3028',
    position: 15,
    nbParagraphs: 2,
    color: '#546545',
    blackText: false,
    img: 'fan.png',
  },
  {
    id: 'carCritic',
    level: 0,
    title: 'G-8748',
    position: 12,
    nbParagraphs: 2,
    color: '#546545',
    blackText: false,
    img: 'car.png',
  },
  {
    id: 'blues',
    level: 3,
    title: 'Z-1984',
    position: 16,
    nbParagraphs: 2,
    color: '#546545',
    blackText: false,
    img: 'blues.png',
  },
  {
    id: 'tortureInstruments',
    level: 3,
    title: 'E-9098',
    position: 4,
    nbParagraphs: 3,
    color: '#546545',
    blackText: false,
    img: 'tortureInstruments.png',
  },
  {
    id: 'jogging',
    level: 0,
    title: 'B-1576',
    position: 17,
    nbParagraphs: 2,
    color: '#546545',
    blackText: false,
    img: 'jogging.png',
  },
  {
    id: 'puppies',
    level: 4,
    title: 'W-6842',
    position: 6,
    nbParagraphs: 2,
    color: '#546545',
    blackText: false,
    img: 'puppies.png',
  },
  {
    id: 'oxygen',
    level: 4,
    title: 'V-3218',
    position: 5,
    nbParagraphs: 2,
    color: '#546545',
    blackText: false,
    img: 'oxygen.png',
  },
  {
    id: 'insomnia',
    level: 1,
    title: 'L-0648',
    position: 14,
    nbParagraphs: 2,
    color: '#546545',
    blackText: false,
    img: 'insomnia.png',
  },
  {
    id: 'tv',
    level: 4,
    title: 'C-4583',
    position: 8,
    nbParagraphs: 2,
    color: '#546545',
    blackText: false,
    img: 'tv.png',
  },
  {
    id: 'machine',
    level: 2,
    title: 'U-9201',
    position: 2,
    nbParagraphs: 1,
    color: '#546545',
    blackText: false,
    img: 'machine.png',
  },
  {
    id: 'skeleton',
    level: 1,
    title: 'M-5454',
    position: 1,
    nbParagraphs: 3,
    color: '#546545',
    blackText: false,
    img: 'skeleton.png',
  },
  {
    id: 'void',
    level: 3,
    title: 'S-8235',
    position: 11,
    nbParagraphs: 4,
    color: '#546545',
    blackText: false,
    img: 'void.png',
  },
  {
    id: 'gala',
    level: 2,
    title: 'E-6480',
    position: 10,
    nbParagraphs: 2,
    color: '#546545',
    blackText: false,
    img: 'gala.png',
  },
  {
    id: 'memories',
    level: 3,
    title: 'L-3478',
    position: 18,
    nbParagraphs: 3,
    color: '#546545',
    blackText: false,
    img: 'memories.png',
  },
  {
    id: 'jumpscare',
    level: 2,
    title: 'J-8321',
    position: 3,
    nbParagraphs: 2,
    color: '#546545',
    blackText: false,
    img: 'jumpscare.png',
  },
  {
    id: 'museum',
    level: 2,
    title: 'M-5594',
    position: 20,
    nbParagraphs: 2,
    color: '#546545',
    blackText: false,
    img: 'museum.png',
  },
  {
    id: 'island',
    level: 0,
    title: 'O-6766',
    position: 7,
    nbParagraphs: 3,
    color: '#546545',
    blackText: false,
    img: 'island.png',
  },
  {
    id: 'glass',
    level: 0,
    title: 'D-9404',
    position: 13,
    nbParagraphs: 2,
    color: '#546545',
    blackText: false,
    img: 'glass.png',
  },
  {
    id: 'watchers',
    level: 4,
    title: 'Y-6916',
    position: 9,
    nbParagraphs: 2,
    color: '#546545',
    blackText: false,
    img: 'watchers.png',
  },
  {
    id: 'ruins',
    level: 1,
    title: 'J-0905',
    position: 19,
    nbParagraphs: 2,
    color: '#546545',
    blackText: false,
    img: 'ruins.png',
  },
];
